theme: jekyll-theme-dinky
title: My Zettld Articles 
description: A repo with some of my articles' summary
paginate: 20

plugins:
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-relative-links
